# Generated by Django 4.1.2 on 2022-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stoploss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scaleupqty', models.DecimalField(decimal_places=1, max_digits=5)),
                ('scaledownqty', models.DecimalField(decimal_places=1, max_digits=5)),
                ('openingrange', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
