# Generated by Django 4.1.2 on 2022-10-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettingsModel',
            new_name='Settings',
        ),
    ]
