# Generated by Django 4.1.2 on 2022-10-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_settingsmodel_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='openingrangebox',
            field=models.BooleanField(default=False),
        ),
    ]
