# Generated by Django 4.1.2 on 2022-10-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_settings_openingrangebox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Preferences',
        ),
    ]
