# Generated by Django 4.1.2 on 2022-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_settings_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='scaledownqty',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='scaleupqty',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
