# Generated by Django 4.1.2 on 2022-10-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_preferences_scaledownqty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='openingrange',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='scaledownqty',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='scaleupqty',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stoploss',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='target',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='time',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=3),
        ),
    ]
