# Generated by Django 4.1.2 on 2022-10-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_preferences_openingrange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='openingrange',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='scaledownqty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='scaleupqty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stoploss',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='target',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='time',
            field=models.IntegerField(default=10),
        ),
    ]
