# Generated by Django 4.1.2 on 2022-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_preferences_openingrange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='scaledownqty',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='scaleupqty',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
