# Generated by Django 4.1.2 on 2022-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_preferences_scaledownqty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='openingrange',
            field=models.FloatField(default=10.0, null=True),
        ),
    ]
