# Generated by Django 4.1.2 on 2022-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_alter_preferences_openingrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='openingrangebox',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
