# Generated by Django 4.1.2 on 2022-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_preferences_openingrangebox'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.CharField(max_length=100)),
                ('entryprice', models.FloatField(default=0.0)),
                ('lastTradedPrice', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=1)),
                ('scaleup', models.IntegerField(default=1)),
                ('scaledown', models.IntegerField(default=1)),
                ('startAlgo', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.CharField(max_length=100)),
                ('exchange_token', models.CharField(max_length=100)),
                ('tradingsymbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_price', models.FloatField(default=0.0)),
                ('expiry', models.CharField(max_length=100)),
                ('tick_size', models.FloatField(default=0.0)),
                ('strike', models.FloatField(default=0.0)),
                ('lot_size', models.IntegerField(default=1)),
                ('instrument_type', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManualWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.CharField(max_length=100)),
                ('entryprice', models.FloatField(default=0.0)),
                ('lastTradedPrice', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=1)),
                ('scaleup', models.IntegerField(default=1)),
                ('scaledown', models.IntegerField(default=1)),
                ('startAlgo', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('entryprice', models.FloatField(default=0.0)),
                ('avgTradedPrice', models.FloatField(default=0.0)),
                ('lastTradedPrice', models.FloatField(default=0.0)),
                ('pnl', models.FloatField(default=0.0)),
                ('unrealised', models.FloatField(default=0.0)),
                ('realised', models.FloatField(default=0.0)),
                ('startAlgo', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
