# Generated by Django 4.1.2 on 2022-11-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_algowatchlist_instrumentstoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.CharField(max_length=100)),
                ('instrumentsToken', models.CharField(default='1111', max_length=100)),
                ('status', models.CharField(default='COMPLETE', max_length=100)),
                ('statusMessage', models.CharField(default='COMPLETE', max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('orderId', models.IntegerField(default=1)),
                ('orderTimestamp', models.CharField(default='2021-05-31 09:18:57', max_length=100)),
                ('orderType', models.CharField(default='LIMIT', max_length=100)),
                ('transactionType', models.CharField(default='BUY', max_length=100)),
                ('avgTradedPrice', models.FloatField(default=0.0)),
                ('product', models.CharField(default='MIS', max_length=100)),
            ],
        ),
    ]
