# Generated by Django 4.1.2 on 2022-11-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderId',
            field=models.CharField(default='1111', max_length=100),
        ),
    ]
