# Generated by Django 4.1.2 on 2022-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_orders_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='algowatchlist',
            name='openPostion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='openPostion',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
