# Generated by Django 4.1.2 on 2022-11-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_algowatchlist_openpostion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algowatchlist',
            name='exchangeType',
            field=models.CharField(default='NFO', max_length=100),
        ),
        migrations.AddField(
            model_name='algowatchlist',
            name='instrumentType',
            field=models.CharField(default='CE', max_length=100),
        ),
        migrations.AddField(
            model_name='algowatchlist',
            name='segment',
            field=models.CharField(default='NFO-FUT', max_length=100),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='exchangeType',
            field=models.CharField(default='NFO', max_length=100),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='instrumentType',
            field=models.CharField(default='CE', max_length=100),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='segment',
            field=models.CharField(default='NFO-FUT', max_length=100),
        ),
    ]
