# Generated by Django 4.1.2 on 2022-11-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_algowatchlist_exchangetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='orderId',
            field=models.CharField(default='1111', max_length=100),
        ),
        migrations.AddField(
            model_name='positions',
            name='slPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='positions',
            name='tgPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
