# Generated by Django 4.1.2 on 2022-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_positions_orderid_positions_slprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algowatchlist',
            name='slHitCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='isBuyClicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='isSellClicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='positionType',
            field=models.CharField(default='BUY', max_length=100),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='slHitCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='positions',
            name='positionType',
            field=models.CharField(default='BUY', max_length=100),
        ),
    ]
