# Generated by Django 4.1.2 on 2022-11-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0018_algowatchlist_slhitcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='scriptName',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='algowatchlist',
            name='slHitCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manualwatchlist',
            name='slHitCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='positions',
            name='positionType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
