# Generated by Django 4.1.2 on 2022-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_preferences_scriptname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCheck', models.DateField(null=True)),
            ],
        ),
    ]
