# Generated by Django 4.1.1 on 2023-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_datetimecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='algowatchlist',
            name='algoStartTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='manualwatchlist',
            name='algoStartTime',
            field=models.DateTimeField(null=True),
        ),
    ]
