# Generated by Django 4.1.1 on 2023-02-06 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0021_algowatchlist_algostarttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
